root: true
parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:cypress/recommended
  - airbnb
plugins:
  - '@typescript-eslint'
  - react
  - react-hooks
  - cypress
  - react-refresh
settings:
  react:
    version: detect
env:
  browser: true
  cypress/globals: true
rules:
  no-console: [2, { "allow": ["warn", "error", "info", "groupCollapsed", "groupEnd"]}]
  # My practice is to use "log" for messages I intend to clean up before merging.
  # All these others reflect the intension that they should be left in the codebase.
  react/jsx-filename-extension: [0]  # Imports don't work if I change extension.
  react/sort-comp: [0]  # Non-alphabetical groupings can make more sense.
  react/jsx-one-expression-per-line: [0]  # Makes punctuation after tab awkward.
  react/prop-types: [0] # Re-enable: https://github.com/vitessce/vitessce/issues/144
  import/prefer-default-export: [0]  # Hit eslint error: SyntaxError: Unexpected token, expected {
  react/react-in-jsx-scope: [0]
  react/jsx-curly-newline: [0]
  react/jsx-no-bind: [0] # Allow passing functions as JSX props
  import/no-extraneous-dependencies: [1]
  react/jsx-props-no-multi-spaces: [0]
  no-plusplus: [0]
  react-refresh/only-export-components: [2, { "checkJS": true }]
overrides:
  - files: 'sites/docs/src/theme/**'
    rules:
      # Allow @theme/ and @docusaurus/ imports
      import/no-unresolved: [0]
  - files: 'sites/docs/src/pages/**'
    rules:
      # Allow @theme/ and @docusaurus/ imports
      import/no-unresolved: [0]