#!/usr/bin/env bash
set -o errexit
set -o pipefail

BRANCH=`git rev-parse --abbrev-ref HEAD`
DATE=`date "+%Y-%m-%d"`
HASH=`git rev-parse --short HEAD`
DOCS_URL_PATH="vitessce-data/docs/$DATE/$HASH"

die() { set +v; echo "$*" 1>&2 ; exit 1; }
git diff --quiet || die 'Uncommitted changes: Stash or commit before pushing docs.'

echo '{
  "note": "This file is regenerated by push-docs.sh.",
  "branch": "'$BRANCH'",
  "date": "'$DATE'",
  "hash": "'$HASH'"
}' > docs/version.json

# Build library...
npm run build-lib:prod
npm link docs/node_modules/react

# Build docs site...
cd docs
npm run build

# The following lines are relative to docs/ directory.
DIST_DIR='build/'
# and add an error page for vitessce.io...
cp ../error.html $DIST_DIR
# and push to S3.
aws s3 cp --recursive $DIST_DIR s3://$DOCS_URL_PATH
TARGET_URL="https://s3.amazonaws.com/$DOCS_URL_PATH/index.html"

echo "- $DATE: [$BRANCH]($TARGET_URL)" >> ../DOCS.md

echo "Deployed to $TARGET_URL"
# Open in browser and see if it works:
open "$TARGET_URL"
