export {
  GLOBAL_LABELS,
  DEFAULT_CELLS_LAYER,
  DEFAULT_MOLECULES_LAYER,
  DEFAULT_NEIGHBORHOODS_LAYER,
  DEFAULT_RASTER_DOMAIN_TYPE,
  DEFAULT_RASTER_LAYER_PROPS,
  DEFAULT_LAYER_TYPE_ORDERING,
  square,
  initializeLayerChannels,
  initializeRasterLayersAndChannels,
  getSourceFromLoader,
  isInterleaved,
  isRgb,
  getNgffAxes,
  getNgffAxesForTiff,
  coordinateTransformationsToMatrix,
} from './spatial.js';
