/* eslint-disable */
import { COORDINATION_TYPES } from './state/coordination';

// Human-readable names of components.
export const COMPONENT_NAMES = {
  description: 'Description',
  status: 'Status',
  genes: 'Genes',
  cellSets: 'Cell Sets',
  scatterplot: 'Scatterplot',
  spatial: 'Spatial',
  heatmap: 'Heatmap',
  layerController: 'Spatial Layers',
  cellSetSizes: 'Cell Set Sizes',
  expressionHistogram: 'Expression Histogram',
  genomicProfiles: 'Genomic Profiles',
  cellSetExpression: 'Cell Set Expression',
  higlass: 'HiGlass',
};

// Human-readable names of coordination types.
export const COORDINATION_TYPE_NAMES = {
  [COORDINATION_TYPES.DATASET]: "Dataset",
  [COORDINATION_TYPES.EMBEDDING_TYPE]: "Embedding Type",
  [COORDINATION_TYPES.EMBEDDING_ZOOM]: "Embedding Zoom",
  [COORDINATION_TYPES.EMBEDDING_ROTATION]: "Embedding Rotation",
  [COORDINATION_TYPES.EMBEDDING_TARGET_X]: "Embedding Target X",
  [COORDINATION_TYPES.EMBEDDING_TARGET_Y]: "Embedding Target Y",
  [COORDINATION_TYPES.EMBEDDING_TARGET_Z]: "Embedding Target Z",
  [COORDINATION_TYPES.EMBEDDING_CELL_SET_POLYGONS_VISIBLE]: "Embedding Cell Set Polygons Visible",
  [COORDINATION_TYPES.EMBEDDING_CELL_SET_LABELS_VISIBLE]: "Embedding Cell Set Labels Visible",
  [COORDINATION_TYPES.EMBEDDING_CELL_SET_LABEL_SIZE]: "Embedding Cell Set Label Size",
  [COORDINATION_TYPES.EMBEDDING_CELL_RADIUS]: "Embedding Cell Radius",
  [COORDINATION_TYPES.SPATIAL_ZOOM]: "Spatial Zoom",
  [COORDINATION_TYPES.SPATIAL_ROTATION]: "Spatial Rotation",
  [COORDINATION_TYPES.SPATIAL_TARGET_X]: "Spatial Target X",
  [COORDINATION_TYPES.SPATIAL_TARGET_Y]: "Spatial Target Y",
  [COORDINATION_TYPES.SPATIAL_TARGET_Z]: "Spatial Target Z",
  [COORDINATION_TYPES.SPATIAL_RASTER_LAYERS]: "Spatial Raster Layers",
  [COORDINATION_TYPES.SPATIAL_CELLS_LAYER]: "Spatial Cells Layer",
  [COORDINATION_TYPES.SPATIAL_MOLECULES_LAYER]: "Spatial Molecules Layer",
  [COORDINATION_TYPES.SPATIAL_NEIGHBORHOODS_LAYER]: "Spatial Neighborhoods Layer",
  [COORDINATION_TYPES.HEATMAP_ZOOM_X]: "Heatmap Zoom X",
  [COORDINATION_TYPES.HEATMAP_ZOOM_Y]: "Heatmap Zoom Y",
  [COORDINATION_TYPES.HEATMAP_TARGET_X]: "Heatmap Target X",
  [COORDINATION_TYPES.HEATMAP_TARGET_Y]: "Heatmap Target Y",
  [COORDINATION_TYPES.GENE_EXPRESSION_COLORMAP]: 'Gene Expression Colormap',
  [COORDINATION_TYPES.GENE_EXPRESSION_COLORMAP_RANGE]: "Gene Expression Colormap Range",
  [COORDINATION_TYPES.GENE_EXPRESSION_TRANSFORM]: "Gene Expression Transform",
  [COORDINATION_TYPES.GENE_FILTER]: "Gene Filter",
  [COORDINATION_TYPES.GENE_HIGHLIGHT]: "Gene Highlight",
  [COORDINATION_TYPES.GENE_SELECTION]: "Gene Selection",
  [COORDINATION_TYPES.CELL_FILTER]: "Cell Filter",
  [COORDINATION_TYPES.CELL_HIGHLIGHT]: "Cell Highlight",
  [COORDINATION_TYPES.CELL_SET_SELECTION]: "Cell Set Selection",
  [COORDINATION_TYPES.CELL_SET_HIGHLIGHT]: "Cell Set Highlight",
  [COORDINATION_TYPES.CELL_SET_COLOR]: "Cell Set Color",
  [COORDINATION_TYPES.CELL_COLOR_ENCODING]: "Cell Color Encoding",
  [COORDINATION_TYPES.GENOMIC_ZOOM_X]: "Genomic Zoom X",
  [COORDINATION_TYPES.GENOMIC_ZOOM_Y]: "Genomic Zoom Y",
  [COORDINATION_TYPES.GENOMIC_TARGET_X]: "Genomic Target X",
  [COORDINATION_TYPES.GENOMIC_TARGET_Y]: "Genomic Target Y",
  [COORDINATION_TYPES.ADDITIONAL_CELL_SETS]: "Additional Cell Sets",
  [COORDINATION_TYPES.MOLECULE_HIGHLIGHT]: "Molecule Highlight",
};