/* eslint-disable import/no-unresolved */
import { Vector2, Vector3 } from 'three';
import vertexShader from '../shaders/VolumeVertexShader.glsl?raw';
import fragmentShader from '../shaders/VolumeFragmentShader.glsl?raw';

export const VolumeShader = {
  uniforms: {
    u_size: { value: new Vector3(1, 1, 1) },
    u_renderstyle: { value: 0 },
    u_renderthreshold: { value: 0.5 },
    u_opacity: { value: 0.5 },
    u_clim: { value: new Vector2(0.2, 0.8) },
    u_clim2: { value: new Vector2(0.2, 0.8) },
    u_clim3: { value: new Vector2(0.2, 0.8) },
    u_clim4: { value: new Vector2(0.2, 0.8) },
    u_clim5: { value: new Vector2(0.2, 0.8) },
    u_clim6: { value: new Vector2(0.2, 0.8) },
    u_xClip: { value: new Vector2(-1.0, 1000000.0) },
    u_yClip: { value: new Vector2(-1.0, 1000000.0) },
    u_zClip: { value: new Vector2(-1.0, 1000000.0) },
    u_data: { value: null },
    u_stop_geom: { value: null },
    u_geo_color: { value: null },
    u_window_size: { value: new Vector2(1, 1) },
    u_vol_scale: { value: new Vector2(1, 1, 1) },
    u_physical_Pixel: { value: 0.5 },
    volumeTex: { value: null },
    volumeTex2: { value: null },
    volumeTex3: { value: null },
    volumeTex4: { value: null },
    volumeTex5: { value: null },
    volumeTex6: { value: null },
    u_color: { value: new Vector3(0, 0, 0) },
    u_color2: { value: new Vector3(0, 0, 0) },
    u_color3: { value: new Vector3(0, 0, 0) },
    u_color4: { value: new Vector3(0, 0, 0) },
    u_color5: { value: new Vector3(0, 0, 0) },
    u_color6: { value: new Vector3(0, 0, 0) },
    u_cmdata: { value: null },
    near: { value: 0.1 },
    far: { value: 10000 },
    alphaScale: { value: 0 },
    dtScale: { value: 1 },
    volumeCount: { value: 0 },
    finalGamma: { value: 0 },
    boxSize: { value: new Vector3(1, 1, 1) },
  },
  vertexShader,
  fragmentShader,
};
