// Here, we re-export all MUI things
// used in the rest of the monorepo packages.
// This is intended to make upgrading MUI easier.
export {
  // Utils
  createTheme,
  colors,
  ThemeProvider,
  StylesProvider,
  makeStyles,
  createStyles, // TODO: remove this usage
  // Components
  Slider,
  Typography,
  Paper,
  Popper,
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Stepper,
  Step,
  StepLabel,
  Tabs,
  Tab,
  InputLabel,
  Button,
  Grid,
  Box,
  ButtonGroup,
  Tooltip,
  TextField,
  FormHelperText,
  Select,
  FormControl,
  RadioGroup,
  FormLabel,
  Radio,
  FormControlLabel,
  Table,
  TableBody,
  TableContainer,
  TableCell,
  TableRow,
  Checkbox,
  Switch,
  IconButton,
  CircularProgress,
  Link,
  MenuList,
  MenuItem,
  ClickAwayListener,
  Fade,
  List,
  ListItem,
  ListItemText,
  FormGroup,
} from '@material-ui/core';
export {
  CloudDownload,
  ArrowDropDown,
  ArrowDropUp,
  Settings,
  Close,
  Help,
  ExpandMore,
  Add,
  Info,
  MoreVert,
  Visibility,
  VisibilityOff,
  Image,
  ExpandLess,
  RemoveCircle,
  Lens,
  CenterFocusStrong,
} from '@material-ui/icons';
export {
  Autocomplete,
} from '@material-ui/lab';
export {
  DataGrid,
} from '@mui/x-data-grid';