export const useSpanStyles: (props?: any) => import("@material-ui/core/styles/withStyles").ClassNameMap<"span">;
export const useChannelSliderStyles: (props?: any) => import("@material-ui/core/styles/withStyles").ClassNameMap<"valueLabel">;
export const useSelectStyles: (props?: any) => import("@material-ui/core/styles/withStyles").ClassNameMap<"selectRoot">;
export const useControllerSectionStyles: (props?: any) => import("@material-ui/core/styles/withStyles").ClassNameMap<"layerControllerRoot" | "layerControllerGrid">;
export const useAccordionStyles: (props?: any) => import("@material-ui/core/styles/withStyles").ClassNameMap<"content" | "expanded" | "accordionDetailsRoot" | "accordionSummaryRoot" | "expandIcon">;
export const useInputLabelStyles: (props?: any) => import("@material-ui/core/styles/withStyles").ClassNameMap<"inputLabelRoot">;
export const useOverflowEllipsisGridStyles: (props?: any) => import("@material-ui/core/styles/withStyles").ClassNameMap<"item">;
export const useSelectionSliderStyles: (props?: any) => import("@material-ui/core/styles/withStyles").ClassNameMap<"selectionSliderRoot" | "markActive">;
//# sourceMappingURL=styles.d.ts.map