export const satija2020 = {
  version: '1.0.15',
  name: 'HBM336.FWTN.636',
  description:
    'Spleen scRNA-seq HuBMAP dataset with cell type annotations generated by the Satija lab and the Seurat v3.1 Label Transfer workflow',
  public: true,
  datasets: [
    {
      uid: '2dca1bf5832a4102ba780e9e54f6c350',
      name: 'HBM336.FWTN.636',
      files: [
        {
          fileType: 'anndata.zarr',
          url: 'https://s3.amazonaws.com/vitessce-data/0.0.33/main/satija-2020/satija_2020.h5ad.zarr',
          coordinationValues: {
            obsType: 'cell',
            featureType: 'gene',
            featureValueType: 'expression',
            embeddingType: 'UMAP',
          },
          options: {
            obsEmbedding: {
              path: 'obsm/X_umap',
            },
            obsFeatureMatrix: {
              path: 'X',
            },
            obsLabels: [
              {
                path: 'obs/prediction_score',
                obsLabelsType: 'Cell Type Annotation Prediction Score',
              },
            ],
          },
        },
        {
          fileType: 'obsSets.json',
          url: 'https://s3.amazonaws.com/vitessce-data/0.0.33/main/satija-2020/satija_2020.cell-sets.json',
          coordinationValues: {
            obsType: 'cell',
          },
        },
      ],
    },
  ],
  initStrategy: 'auto',
  coordinationSpace: {
    embeddingType: {
      UMAP: 'UMAP',
    },
    obsLabelsType: {
      A: 'Cell Type Annotation Prediction Score',
    },
    embeddingZoom: {
      A: 3,
    },
    embeddingTargetX: {
      A: 0,
    },
    embeddingTargetY: {
      A: 0,
    },
    spatialZoom: {
      A: 3,
    },
    spatialTargetX: {
      A: 0,
    },
    spatialTargetY: {
      A: 0,
    },
    featureValueColormapRange: {
      A: [0, 0.25],
    },
  },
  layout: [
    {
      component: 'obsSets',
      h: 4,
      w: 4,
      x: 4,
      y: 0,
      coordinationScopes: {},
    },
    {
      component: 'obsSetSizes',
      h: 4,
      w: 4,
      x: 8,
      y: 0,
      coordinationScopes: {},
    },
    {
      component: 'scatterplot',
      h: 4,
      w: 4,
      x: 0,
      y: 0,
      coordinationScopes: {
        embeddingType: 'UMAP',
        embeddingZoom: 'A',
        embeddingTargetX: 'A',
        embeddingTargetY: 'A',
        obsLabelsType: ['A'],
      },
    },
    {
      component: 'heatmap',
      h: 4,
      w: 10,
      x: 0,
      y: 4,
      coordinationScopes: {
        featureValueColormapRange: 'A',
        obsLabelsType: ['A'],
      },
      props: {
        transpose: false,
      },
    },
    {
      component: 'description',
      h: 4,
      w: 2,
      x: 10,
      y: 4,
    },
  ],
};
