import { CoordinationType, ViewType } from '../constants';

export const DEFAULT_ENTITY_TYPE_VALUES = {
  [CoordinationType.OBS_TYPE]: 'cell',
  [CoordinationType.SUB_OBS_TYPE]: 'molecule',
  [CoordinationType.FEATURE_TYPE]: 'gene',
  [CoordinationType.SUB_FEATURE_TYPE]: 'isoform',
  [CoordinationType.FEATURE_VALUE_TYPE]: 'expression',
  [CoordinationType.SUB_FEATURE_VALUE_TYPE]: 'intensity',
};

export const ENTITY_COORDINATION_TYPES = Object
  .keys(DEFAULT_ENTITY_TYPE_VALUES);

/**
 * Coordination types may have default values,
 * which can be defined here, and used by the
 * auto initialization strategy.
 */
export const DEFAULT_COORDINATION_VALUES = {
  ...DEFAULT_ENTITY_TYPE_VALUES,
  [CoordinationType.OBS_FILTER]: null,
  [CoordinationType.OBS_HIGHLIGHT]: null,
  [CoordinationType.OBS_SELECTION]: null,
  [CoordinationType.OBS_SET_SELECTION]: null,
  [CoordinationType.OBS_SET_HIGHLIGHT]: null,
  [CoordinationType.OBS_SET_COLOR]: null,
  [CoordinationType.OBS_COLOR_ENCODING]: 'obsSetSelection',

  [CoordinationType.SUB_OBS_FILTER]: null,
  [CoordinationType.SUB_OBS_HIGHLIGHT]: null,
  [CoordinationType.SUB_OBS_SELECTION]: null,
  [CoordinationType.SUB_OBS_SET_SELECTION]: null,
  [CoordinationType.SUB_OBS_SET_HIGHLIGHT]: null,
  [CoordinationType.SUB_OBS_SET_COLOR]: null,
  [CoordinationType.SUB_OBS_COLOR_ENCODING]: 'subObsSetSelection',

  [CoordinationType.FEATURE_FILTER]: null,
  [CoordinationType.FEATURE_HIGHLIGHT]: null,
  [CoordinationType.FEATURE_SELECTION]: null,
  [CoordinationType.FEATURE_SET_SELECTION]: null,
  [CoordinationType.FEATURE_SET_HIGHLIGHT]: null,
  [CoordinationType.FEATURE_SET_COLOR]: null,

  [CoordinationType.SUB_FEATURE_FILTER]: null,
  [CoordinationType.SUB_FEATURE_HIGHLIGHT]: null,
  [CoordinationType.SUB_FEATURE_SELECTION]: null,
  [CoordinationType.SUB_FEATURE_SET_SELECTION]: null,
  [CoordinationType.SUB_FEATURE_SET_HIGHLIGHT]: null,
  [CoordinationType.SUB_FEATURE_SET_COLOR]: null,

  [CoordinationType.FEATURE_VALUE_COLORMAP]: 'plasma',
  [CoordinationType.FEATURE_VALUE_COLORMAP_RANGE]: [0.0, 1.0],
  [CoordinationType.FEATURE_VALUE_TRANSFORM]: null,

  [CoordinationType.SUB_FEATURE_VALUE_COLORMAP]: 'plasma',
  [CoordinationType.SUB_FEATURE_VALUE_COLORMAP_RANGE]: [0.0, 1.0],
  [CoordinationType.SUB_FEATURE_VALUE_TRANSFORM]: null,

  [CoordinationType.EMBEDDING_ZOOM]: null,
  [CoordinationType.EMBEDDING_ROTATION]: 0,
  [CoordinationType.EMBEDDING_TARGET_X]: null,
  [CoordinationType.EMBEDDING_TARGET_Y]: null,
  [CoordinationType.EMBEDDING_TARGET_Z]: 0,
  [CoordinationType.EMBEDDING_OBS_SET_POLYGONS_VISIBLE]: false,
  [CoordinationType.EMBEDDING_OBS_SET_LABELS_VISIBLE]: false,
  [CoordinationType.EMBEDDING_OBS_SET_LABEL_SIZE]: 14,
  [CoordinationType.EMBEDDING_OBS_RADIUS]: 1,
  [CoordinationType.EMBEDDING_OBS_RADIUS_MODE]: 'auto',
  [CoordinationType.EMBEDDING_OBS_OPACITY]: 1,
  [CoordinationType.EMBEDDING_OBS_OPACITY_MODE]: 'auto',
  [CoordinationType.SPATIAL_ZOOM]: null,
  [CoordinationType.SPATIAL_ROTATION]: 0,
  [CoordinationType.SPATIAL_TARGET_X]: null,
  [CoordinationType.SPATIAL_TARGET_Y]: null,
  [CoordinationType.SPATIAL_TARGET_Z]: null,
  [CoordinationType.SPATIAL_ROTATION_X]: null,
  [CoordinationType.SPATIAL_ROTATION_Y]: null,
  [CoordinationType.SPATIAL_ROTATION_Z]: null,
  [CoordinationType.SPATIAL_AXIS_FIXED]: false,
  [CoordinationType.SPATIAL_ROTATION_ORBIT]: 0,
  [CoordinationType.SPATIAL_ORBIT_AXIS]: 'Y',
  [CoordinationType.SPATIAL_RASTER_LAYERS]: null,
  [CoordinationType.SPATIAL_OBS_LAYER]: null,
  [CoordinationType.SPATIAL_SUB_OBS_LAYER]: null,
  [CoordinationType.SPATIAL_NEIGHBORHOODS_LAYER]: null,
  [CoordinationType.HEATMAP_ZOOM_X]: 0,
  [CoordinationType.HEATMAP_ZOOM_Y]: 0,
  [CoordinationType.HEATMAP_TARGET_X]: 0,
  [CoordinationType.HEATMAP_TARGET_Y]: 0,

  [CoordinationType.GENOMIC_ZOOM_X]: 0,
  [CoordinationType.GENOMIC_ZOOM_Y]: 0,
  [CoordinationType.GENOMIC_TARGET_X]: 1549999999.5,
  [CoordinationType.GENOMIC_TARGET_Y]: 1549999999.5,
  [CoordinationType.ADDITIONAL_OBS_SETS]: null,
  [CoordinationType.ADDITIONAL_SUB_OBS_SETS]: null,
  [CoordinationType.ADDITIONAL_FEATURE_SETS]: null,
  [CoordinationType.ADDITIONAL_SUB_FEATURE_SETS]: null,
};

// The following coordination types should be
// initialized to independent scopes when
// initialized automatically.
// These make the resulting view config
// (after auto-initialization) behave
// like "legacy" Vitessce (pre-coordination model).
export const AUTO_INDEPENDENT_COORDINATION_TYPES = [
  CoordinationType.HEATMAP_ZOOM_X,
  CoordinationType.HEATMAP_ZOOM_Y,
  CoordinationType.HEATMAP_TARGET_X,
  CoordinationType.HEATMAP_TARGET_Y,
  CoordinationType.EMBEDDING_ZOOM,
  CoordinationType.EMBEDDING_TARGET_X,
  CoordinationType.EMBEDDING_TARGET_Y,
  CoordinationType.EMBEDDING_TARGET_Z,
  CoordinationType.EMBEDDING_OBS_SET_POLYGONS_VISIBLE,
  CoordinationType.EMBEDDING_OBS_SET_LABELS_VISIBLE,
  CoordinationType.EMBEDDING_OBS_SET_LABEL_SIZE,
  CoordinationType.EMBEDDING_OBS_RADIUS,
  CoordinationType.EMBEDDING_OBS_OPACITY,
];

/**
   * Mapping from component type to
   * supported coordination object types.
   * This mapping can be used to determine
   * which pieces of state that a component will
   * need to get/set.
   * Keys here are the component registry keys.
   */
export const COMPONENT_COORDINATION_TYPES = {
  [ViewType.OBS_SCATTERPLOT]: [
    CoordinationType.DATASET,
    ...ENTITY_COORDINATION_TYPES,
    CoordinationType.EMBEDDING_TYPE,
    CoordinationType.EMBEDDING_ZOOM,
    CoordinationType.EMBEDDING_ROTATION,
    CoordinationType.EMBEDDING_TARGET_X,
    CoordinationType.EMBEDDING_TARGET_Y,
    CoordinationType.EMBEDDING_TARGET_Z,
    CoordinationType.EMBEDDING_OBS_SET_POLYGONS_VISIBLE,
    CoordinationType.EMBEDDING_OBS_SET_LABELS_VISIBLE,
    CoordinationType.EMBEDDING_OBS_SET_LABEL_SIZE,
    CoordinationType.EMBEDDING_OBS_RADIUS,
    CoordinationType.EMBEDDING_OBS_RADIUS_MODE,
    CoordinationType.EMBEDDING_OBS_OPACITY,
    CoordinationType.EMBEDDING_OBS_OPACITY_MODE,
    CoordinationType.OBS_FILTER,
    CoordinationType.OBS_HIGHLIGHT,
    CoordinationType.OBS_SET_SELECTION,
    CoordinationType.OBS_SET_HIGHLIGHT,
    CoordinationType.OBS_SET_COLOR,
    CoordinationType.FEATURE_HIGHLIGHT,
    CoordinationType.FEATURE_SELECTION,
    CoordinationType.FEATURE_VALUE_COLORMAP,
    CoordinationType.FEATURE_VALUE_COLORMAP_RANGE,
    CoordinationType.OBS_COLOR_ENCODING,
    CoordinationType.ADDITIONAL_OBS_SETS,
  ],
  [ViewType.SPATIAL]: [
    CoordinationType.DATASET,
    ...ENTITY_COORDINATION_TYPES,
    CoordinationType.SPATIAL_ZOOM,
    CoordinationType.SPATIAL_ROTATION,
    CoordinationType.SPATIAL_RASTER_LAYERS,
    CoordinationType.SPATIAL_OBS_LAYER,
    CoordinationType.SPATIAL_SUB_OBS_LAYER,
    CoordinationType.SPATIAL_NEIGHBORHOODS_LAYER,
    CoordinationType.SPATIAL_TARGET_X,
    CoordinationType.SPATIAL_TARGET_Y,
    CoordinationType.SPATIAL_TARGET_Z,
    CoordinationType.SPATIAL_ROTATION_X,
    CoordinationType.SPATIAL_ROTATION_Y,
    CoordinationType.SPATIAL_ROTATION_Z,
    CoordinationType.SPATIAL_ROTATION_ORBIT,
    CoordinationType.SPATIAL_ORBIT_AXIS,
    CoordinationType.SPATIAL_AXIS_FIXED,
    CoordinationType.OBS_FILTER,
    CoordinationType.OBS_HIGHLIGHT,
    CoordinationType.OBS_SET_SELECTION,
    CoordinationType.OBS_SET_HIGHLIGHT,
    CoordinationType.OBS_SET_COLOR,
    CoordinationType.FEATURE_HIGHLIGHT,
    CoordinationType.FEATURE_SELECTION,
    CoordinationType.FEATURE_VALUE_COLORMAP,
    CoordinationType.FEATURE_VALUE_COLORMAP_RANGE,
    CoordinationType.OBS_COLOR_ENCODING,
    CoordinationType.ADDITIONAL_OBS_SETS,
    CoordinationType.SUB_OBS_HIGHLIGHT,
  ],
  [ViewType.HEATMAP]: [
    CoordinationType.DATASET,
    ...ENTITY_COORDINATION_TYPES,
    CoordinationType.HEATMAP_ZOOM_X,
    CoordinationType.HEATMAP_ZOOM_Y,
    CoordinationType.HEATMAP_TARGET_X,
    CoordinationType.HEATMAP_TARGET_Y,
    CoordinationType.OBS_FILTER,
    CoordinationType.OBS_HIGHLIGHT,
    CoordinationType.OBS_SET_SELECTION,
    CoordinationType.OBS_SET_HIGHLIGHT,
    CoordinationType.OBS_SET_COLOR,
    CoordinationType.FEATURE_FILTER,
    CoordinationType.FEATURE_HIGHLIGHT,
    CoordinationType.FEATURE_SELECTION,
    CoordinationType.FEATURE_VALUE_COLORMAP,
    CoordinationType.FEATURE_VALUE_COLORMAP_RANGE,
    CoordinationType.OBS_COLOR_ENCODING,
    CoordinationType.ADDITIONAL_OBS_SETS,
  ],
  [ViewType.OBS_SETS]: [
    CoordinationType.DATASET,
    ...ENTITY_COORDINATION_TYPES,
    CoordinationType.OBS_SET_SELECTION,
    CoordinationType.OBS_SET_HIGHLIGHT,
    CoordinationType.OBS_SET_COLOR,
    CoordinationType.OBS_COLOR_ENCODING,
    CoordinationType.ADDITIONAL_OBS_SETS,
    CoordinationType.FEATURE_SELECTION,
  ],
  [ViewType.OBS_SET_SIZES]: [
    CoordinationType.DATASET,
    ...ENTITY_COORDINATION_TYPES,
    CoordinationType.OBS_SET_SELECTION,
    CoordinationType.OBS_SET_HIGHLIGHT,
    CoordinationType.OBS_SET_COLOR,
    CoordinationType.ADDITIONAL_OBS_SETS,
  ],
  [ViewType.STATUS]: [
    CoordinationType.DATASET,
    ...ENTITY_COORDINATION_TYPES,
    CoordinationType.OBS_HIGHLIGHT,
    CoordinationType.FEATURE_HIGHLIGHT,
    CoordinationType.OBS_SET_HIGHLIGHT,
    CoordinationType.SUB_OBS_HIGHLIGHT,
  ],
  [ViewType.FEATURES]: [
    CoordinationType.DATASET,
    ...ENTITY_COORDINATION_TYPES,
    CoordinationType.FEATURE_FILTER,
    CoordinationType.FEATURE_HIGHLIGHT,
    CoordinationType.FEATURE_SELECTION,
    CoordinationType.OBS_COLOR_ENCODING,
    CoordinationType.OBS_SET_SELECTION,
  ],
  [ViewType.OBS_SET_FEATURE_DISTRIBUTION]: [
    CoordinationType.DATASET,
    ...ENTITY_COORDINATION_TYPES,
    CoordinationType.FEATURE_SELECTION,
    CoordinationType.FEATURE_VALUE_TRANSFORM,
    CoordinationType.OBS_SET_SELECTION,
    CoordinationType.OBS_SET_HIGHLIGHT,
    CoordinationType.OBS_SET_COLOR,
    CoordinationType.ADDITIONAL_OBS_SETS,
  ],
  [ViewType.FEATURE_VALUE_HISTOGRAM]: [
    CoordinationType.DATASET,
    ...ENTITY_COORDINATION_TYPES,
    CoordinationType.FEATURE_SELECTION,
  ],
  [ViewType.LAYER_CONTROLLER]: [
    CoordinationType.DATASET,
    ...ENTITY_COORDINATION_TYPES,
    CoordinationType.SPATIAL_RASTER_LAYERS,
    CoordinationType.SPATIAL_OBS_LAYER,
    CoordinationType.SPATIAL_SUB_OBS_LAYER,
    CoordinationType.SPATIAL_NEIGHBORHOODS_LAYER,
    CoordinationType.SPATIAL_ZOOM,
    CoordinationType.SPATIAL_TARGET_X,
    CoordinationType.SPATIAL_TARGET_Y,
    CoordinationType.SPATIAL_TARGET_Z,
    CoordinationType.SPATIAL_ROTATION_X,
    CoordinationType.SPATIAL_ROTATION_Y,
    CoordinationType.SPATIAL_ROTATION_Z,
    CoordinationType.SPATIAL_ROTATION_ORBIT,
    CoordinationType.SPATIAL_ORBIT_AXIS,
  ],
  [ViewType.GENOMIC_PROFILES]: [
    CoordinationType.DATASET,
    ...ENTITY_COORDINATION_TYPES,
    CoordinationType.GENOMIC_ZOOM_X,
    CoordinationType.GENOMIC_ZOOM_Y,
    CoordinationType.GENOMIC_TARGET_X,
    CoordinationType.GENOMIC_TARGET_Y,
    CoordinationType.FEATURE_FILTER,
    CoordinationType.FEATURE_HIGHLIGHT,
    CoordinationType.FEATURE_SELECTION,
    CoordinationType.OBS_SET_SELECTION,
    CoordinationType.OBS_SET_HIGHLIGHT,
    CoordinationType.OBS_SET_COLOR,
    CoordinationType.ADDITIONAL_OBS_SETS,
  ],
  [ViewType.DESCRIPTION]: [
    CoordinationType.DATASET,
    ...ENTITY_COORDINATION_TYPES,
    CoordinationType.SPATIAL_RASTER_LAYERS,
  ],
  higlass: [
    CoordinationType.DATASET,
    ...ENTITY_COORDINATION_TYPES,
    CoordinationType.GENOMIC_ZOOM_X,
    CoordinationType.GENOMIC_ZOOM_Y,
    CoordinationType.GENOMIC_TARGET_X,
    CoordinationType.GENOMIC_TARGET_Y,
    CoordinationType.FEATURE_FILTER,
    CoordinationType.FEATURE_HIGHLIGHT,
    CoordinationType.FEATURE_SELECTION,
  ],
};
